Repository EpicMorg/atlassian-downloader, pull requests merged in 2023-10, with the labels that each got.

#32 1.1.0.0
  src/DonloaderService.cs
  src/atlassian-downloader.csproj
Labels: enhancement, improvements

#40 Feature/2.0
  .github/workflows/dotnet-develop.yml
  .github/workflows/dotnet-master.yml
  CHANGELOG.md
  README.md
  src/Core/BellsAndWhistles.cs
  src/Core/DownloaderService.cs
  src/DonloaderService.cs
  src/Models/DownloadAction.cs
  src/Models/DownloaderOptions.cs
  src/Models/ResponseItem.cs
  src/Models/SourceInformation.cs
  src/Program.cs
  src/Properties/PublishProfiles/linux-arm.pubxml
  src/Properties/PublishProfiles/linux-arm.user
  src/Properties/PublishProfiles/linux-arm64.pubxml
  src/Properties/PublishProfiles/linux-arm64.user
  src/Properties/PublishProfiles/linux-bionic-x64.pubxml
  src/Properties/PublishProfiles/linux-bionic-x64.user
  src/Properties/PublishProfiles/linux-musl-x64.pubxml
  src/Properties/PublishProfiles/linux-musl-x64.user
  src/Properties/PublishProfiles/linux-x64.pubxml
  src/Properties/PublishProfiles/linux-x64.user
  src/Properties/PublishProfiles/osx-arm64.pubxml
  src/Properties/PublishProfiles/osx-arm64.user
  src/Properties/PublishProfiles/osx-x64.pubxml
  src/Properties/PublishProfiles/osx-x64.user
  src/Properties/PublishProfiles/win-arm64.pubxml
  src/Properties/PublishProfiles/win-arm64.user
  src/Properties/PublishProfiles/win-x64.pubxml
  src/Properties/PublishProfiles/win-x64.pubxml.user
  src/Properties/PublishProfiles/win-x86.pubxml
  src/Properties/PublishProfiles/win-x86.pubxml.user
  src/Properties/launchSettings.json
  src/atlassian-downloader.csproj
  src/build.bat
  src/build.sh
Labels: enhancement, improvements, new feature

#42 Remove redundant parameters from publish profiles
  src/Properties/PublishProfiles/linux-arm.pubxml
  src/Properties/PublishProfiles/linux-arm64.pubxml
  src/Properties/PublishProfiles/linux-bionic-x64.pubxml
  src/Properties/PublishProfiles/linux-musl-x64.pubxml
  src/Properties/PublishProfiles/linux-x64.pubxml
  src/Properties/PublishProfiles/osx-arm64.pubxml
  src/Properties/PublishProfiles/osx-x64.pubxml
  src/Properties/PublishProfiles/win-arm64.pubxml
  src/Properties/PublishProfiles/win-x64.pubxml
  src/Properties/PublishProfiles/win-x86.pubxml
Labels: bug

#43 Fix default output dir, enable nullables, fix compiler warnings
  src/Core/BellsAndWhistles.cs
  src/Core/DownloaderService.cs
  src/Models/DownloaderOptions.cs
  src/Models/ResponseItem.cs
  src/Program.cs
  src/atlassian-downloader.csproj
Labels: bug
